### ISSUE TITLE
8188eu on raspberry pi (kernel 3.12.13+)

### ISSUE THREAD

**Issue by FishTest** [lwfinger/rtl8188eu#104]
When i executed:
pi@raspberrypi ~ $ sudo ifconfig wlan0 up
SIOCSIFFLAGS: Operation not permitted

pi@raspberrypi ~ $ dmesg
[ 1782.730609] Request firmware failed with error 0xfffffffe

pi@raspberrypi ~/rtl8188eu $ uname -a
Linux raspberrypi 3.12.13-rt21 #3 PREEMPT RT Sat Feb 28 08:59:16 UTC 2015 armv6l GNU/Linux

pi@raspberrypi ~/rtl8188eu $ modinfo 8188eu.ko
filename:       /home/pi/rtl8188eu/8188eu.ko
version:        v4.1.4_6773.20130222
author:         Realtek Semiconductor Corp.
description:    Realtek Wireless Lan Driver
license:        GPL
srcversion:     2BAA5464C3559005A618742
alias:          usb:v056Ep4008d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2001p3311d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2001p3310d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2001p330Fd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0DF6p0076d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v07B8p8179d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp0179d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp8179d*dc*dsc*dp*ic*isc*ip*in*
depends:
vermagic:       3.12.13-rt21 preempt mod_unload modversions ARMv6
parm:           rtw_ips_mode:The default IPS mode (int)
parm:           ifname:The default name to allocate for first interface (charp)
parm:           if2name:The default name to allocate for second interface (charp)
parm:           rtw_initmac:charp
parm:           rtw_channel_plan:int
parm:           rtw_chip_version:int
parm:           rtw_rfintfs:int
parm:           rtw_lbkmode:int
parm:           rtw_network_mode:int
parm:           rtw_channel:int
parm:           rtw_mp_mode:int
parm:           rtw_wmm_enable:int
parm:           rtw_vrtl_carrier_sense:int
parm:           rtw_vcs_type:int
parm:           rtw_busy_thresh:int
parm:           rtw_ht_enable:int
parm:           rtw_cbw40_enable:int
parm:           rtw_ampdu_enable:int
parm:           rtw_rx_stbc:int
parm:           rtw_ampdu_amsdu:int
parm:           rtw_lowrate_two_xmit:int
parm:           rtw_rf_config:int
parm:           rtw_power_mgnt:int
parm:           rtw_smart_ps:int
parm:           rtw_low_power:int
parm:           rtw_wifi_spec:int
parm:           rtw_antdiv_cfg:int
parm:           rtw_antdiv_type:int
parm:           rtw_enusbss:int
parm:           rtw_hwpdn_mode:int
parm:           rtw_hwpwrp_detect:int
parm:           rtw_hw_wps_pbc:int
parm:           rtw_max_roaming_times:The max roaming times to try (uint)
parm:           rtw_fw_iol:FW IOL (int)
parm:           rtw_mc2u_disable:int
parm:           rtw_80211d:Enable 802.11d mechanism (int)
parm:           rtw_notch_filter:0:Disable, 1:Enable, 2:Enable only for P2P (uint)
parm:           debug:Set debug level (1-9) (default 1) (int)

pi@raspberrypi ~ $ lshw -C network
WARNING: you should run this program as super-user.
  *-network:0 DISABLED
       description: Wireless interface
       physical id: 1
       bus info: usb@1:1.1
       logical name: wlan0
       serial: 08:57:00:a2:17:13
       capabilities: ethernet physical wireless
       configuration: broadcast=yes driver=r8188eu ip=192.168.1.10 multicast=yes wireless=unassociated

pi@raspberrypi ~ $ lsmod
Module                  Size  Used by
8188eu                736583  0
joydev                  9085  0
rp_usbdisplay          13452  3
asix                   18908  0
libphy                 26688  1 asix
leds_gpio               2114  0
led_class               4199  1 leds_gpio
evdev                  10434  4

pi@raspberrypi ~ $ lsusb
Bus 001 Device 002: ID 1a40:0101 Terminus Technology Inc. 4-Port HUB
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0bda:8179 Realtek Semiconductor Corp.
Bus 001 Device 004: ID 0b95:772b ASIX Electronics Corp.

How to solve this problem?

**Comment by FishTest** [comment]
and how to set 8188eu work in ap mode when modprobe?

**Comment by lwfinger** [comment]
To solve the first problem, install the firmware. If you had used 'sudo make install', that step would have been done for you.

To use it as an AP, the master branch needs to use version 0.8 of hostapd. If you switch to branch v4.1.8_9499, then you can use a new version of hostapd.

**Comment by FishTest** [comment]
Thanks! i've rebuild rpi linux kernel on rpi and rebuild your 8188eu driver,and it works.
