### ISSUE TITLE
Oops/Segfault on Raspberry Pi / Raspbian / Debian Wheezy

### ISSUE THREAD

**Issue by sebastianbergmann** [lwfinger/rtl8188eu#129]
## Relevant section

    [   74.249606] Unable to handle kernel paging request at virtual address 7e32d254
    [   74.261993] pgd = dd18c000
    [   74.270985] [7e32d254] *pgd=00000000
    [   74.280001] Internal error: Oops: 5 [#1] PREEMPT ARM
    [   74.289880] Modules linked in: 8188eu(O+) cfg80211 rfkill snd_bcm2835 snd_pcm snd_seq snd_seq_device snd_timer snd evdev joydev uio_pdrv_genirq uio
    [   74.308698] CPU: 0 PID: 2329 Comm: modprobe Tainted: G           O   3.18.11+ #781
    [   74.321564] task: dd245100 ti: ddfd4000 task.ti: ddfd4000
    [   74.332279] PC is at load_module+0x1948/0x1f1c
    [   74.341811] LR is at load_module+0x1934/0x1f1c
    [   74.351490] pc : [<c00886d0>]    lr : [<c00886bc>]    psr: 30000013
    [   74.351490] sp : ddfd5e88  ip : bf1a81c0  fp : ddfd5f44
    [   74.373345] r10: bf1a8058  r9 : 00000000  r8 : bf1a8064
    [   74.383843] r7 : c0557314  r6 : dd3ef4e0  r5 : 7e32d240  r4 : ddfd5f48
    [   74.395550] r3 : 00000000  r2 : 00000000  r1 : da5b7dc0  r0 : c0814280
    [   74.407339] Flags: nzCV  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
    [   74.419872] Control: 00c5387d  Table: 1d18c008  DAC: 00000015
    [   74.431055] Process modprobe (pid: 2329, stack limit = 0xddfd41b0)
    [   74.442519] Stack: (0xddfd5e88 to 0xddfd6000)
    [   74.452377] 5e80:                   bf1a8064 00007fff c0085714 c02fcd88 00000013 00000000
    [   74.466125] 5ea0: df9ae000 ddfd5f7c ddfd5f50 ddfd5eb8 00000000 bf1a8064 ddfd4008 bf1a80a0
    [   74.479747] 5ec0: bf1a81c0 00000000 b6cd0000 ddfd4000 00002db0 00000000 00000000 00000000
    [   74.493403] 5ee0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    [   74.507108] 5f00: 00000000 00000000 00000000 00000000 00000000 00000000 00000080 000e9725
    [   74.520767] 5f20: b6bec000 b6f02948 00000080 c000eaa8 ddfd4000 00000000 ddfd5fa4 ddfd5f48
    [   74.534393] 5f40: c0088d90 c0086d94 df9ae000 000e9725 dfa4f344 dfa4f1d6 dfa8d044 000a1ccc
    [   74.547937] 5f60: 000b245c 00000000 00000000 00000000 00000023 00000024 00000018 0000001c
    [   74.561425] 5f80: 0000000c 00000000 00000000 00000000 00060000 b74df608 00000000 ddfd5fa8
    [   74.574972] 5fa0: c000e800 c0088cb0 00000000 00060000 b6bec000 000e9725 b6f02948 b6bec000
    [   74.588535] 5fc0: 00000000 00060000 b74df608 00000080 b74ded58 000e9725 b6f02948 00000000
    [   74.602120] 5fe0: 00000000 befe090c b6ef9fb4 b6e64e94 60000010 b6bec000 00000000 00000000
    [   74.615733] [<c00886d0>] (load_module) from [<c0088d90>] (SyS_init_module+0xec/0x100)
    [   74.628903] [<c0088d90>] (SyS_init_module) from [<c000e800>] (ret_fast_syscall+0x0/0x48)
    [   74.642434] Code: e51bc084 e15c0005 e2455008 0a000009 (e5953014) 
    [   74.659323] ---[ end trace 9b95a96a348bea3c ]---

## Full log

    [    0.000000] Booting Linux on physical CPU 0x0
    [    0.000000] Initializing cgroup subsys cpu
    [    0.000000] Initializing cgroup subsys cpuacct
    [    0.000000] Linux version 3.18.11+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #781 PREEMPT Tue Apr 21 18:02:18 BST 2015
    [    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
    [    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
    [    0.000000] Machine model: Raspberry Pi Model B Plus
    [    0.000000] cma: Reserved 8 MiB at 0x1e800000
    [    0.000000] Memory policy: Data cache writeback
    [    0.000000] On node 0 totalpages: 126976
    [    0.000000] free_area_init_node: node 0, pgdat c083d364, node_mem_map de414000
    [    0.000000]   Normal zone: 992 pages used for memmap
    [    0.000000]   Normal zone: 0 pages reserved
    [    0.000000]   Normal zone: 126976 pages, LIFO batch:31
    [    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
    [    0.000000] pcpu-alloc: [0] 0 
    [    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 125984
    [    0.000000] Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=1776 bcm2708_fb.fbheight=952 bcm2708.boardrev=0x10 bcm2708.serial=0x7e814aa1 smsc95xx.macaddr=B8:27:EB:81:4A:A1 bcm2708_fb.fbswap=1 bcm2708.disk_led_gpio=47 bcm2708.disk_led_active_low=0 sdhci-bcm2708.emmc_clock_freq=250000000 vc_mem.mem_base=0x1fa00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p6 rootfstype=ext4 elevator=deadline rootwait
    [    0.000000] PID hash table entries: 2048 (order: 1, 8192 bytes)
    [    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
    [    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
    [    0.000000] Memory: 486044K/507904K available (5881K kernel code, 348K rwdata, 1868K rodata, 336K init, 733K bss, 21860K reserved)
    [    0.000000] Virtual kernel memory layout:
    [    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
    [    0.000000]     fixmap  : 0xffc00000 - 0xffe00000   (2048 kB)
    [    0.000000]     vmalloc : 0xdf800000 - 0xff000000   ( 504 MB)
    [    0.000000]     lowmem  : 0xc0000000 - 0xdf000000   ( 496 MB)
    [    0.000000]     modules : 0xbf000000 - 0xc0000000   (  16 MB)
    [    0.000000]       .text : 0xc0008000 - 0xc07997a0   (7750 kB)
    [    0.000000]       .init : 0xc079a000 - 0xc07ee000   ( 336 kB)
    [    0.000000]       .data : 0xc07ee000 - 0xc084513c   ( 349 kB)
    [    0.000000]        .bss : 0xc084513c - 0xc08fc8a8   ( 734 kB)
    [    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
    [    0.000000] Preemptible hierarchical RCU implementation.
    [    0.000000] NR_IRQS:522
    [    0.000025] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 2147483648000ns
    [    0.000074] Switching to timer-based delay loop, resolution 1000ns
    [    0.000357] Console: colour dummy device 80x30
    [    0.001436] console [tty1] enabled
    [    0.001482] Calibrating delay loop (skipped), value calculated using timer frequency.. 2.00 BogoMIPS (lpj=10000)
    [    0.001557] pid_max: default: 32768 minimum: 301
    [    0.001936] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
    [    0.002002] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
    [    0.003007] Initializing cgroup subsys memory
    [    0.003100] Initializing cgroup subsys devices
    [    0.003159] Initializing cgroup subsys freezer
    [    0.003213] Initializing cgroup subsys net_cls
    [    0.003263] Initializing cgroup subsys blkio
    [    0.003381] CPU: Testing write buffer coherency: ok
    [    0.003494] ftrace: allocating 19232 entries in 57 pages
    [    0.108363] Setting up static identity map for 0x553398 - 0x5533d0
    [    0.111203] devtmpfs: initialized
    [    0.128679] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
    [    0.131704] pinctrl core: initialized pinctrl subsystem
    [    0.134383] NET: Registered protocol family 16
    [    0.139891] DMA: preallocated 4096 KiB pool for atomic coherent allocations
    [    0.141342] bcm2708.uart_clock = 3000000
    [    0.144273] No ATAGs?
    [    0.144337] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
    [    0.144400] hw-breakpoint: maximum watchpoint size is 4 bytes.
    [    0.144464] mailbox: Broadcom VideoCore Mailbox driver
    [    0.144624] bcm2708_vcio: mailbox at f200b880
    [    0.145079] bcm_power: Broadcom power driver
    [    0.145135] bcm_power_open() -> 0
    [    0.145165] bcm_power_request(0, 8)
    [    0.645881] bcm_mailbox_read -> 00000080, 0
    [    0.645930] bcm_power_request -> 0
    [    0.646131] Serial: AMBA PL011 UART driver
    [    0.646368] dev:f1: ttyAMA0 at MMIO 0x20201000 (irq = 83, base_baud = 0) is a PL011 rev3
    [    1.033267] console [ttyAMA0] enabled
    [    1.096524] SCSI subsystem initialized
    [    1.100664] usbcore: registered new interface driver usbfs
    [    1.106454] usbcore: registered new interface driver hub
    [    1.111957] usbcore: registered new device driver usb
    [    1.119122] Switched to clocksource stc
    [    1.151506] FS-Cache: Loaded
    [    1.154822] CacheFiles: Loaded
    [    1.174159] NET: Registered protocol family 2
    [    1.180141] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
    [    1.187323] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
    [    1.194106] TCP: Hash tables configured (established 4096 bind 4096)
    [    1.200626] TCP: reno registered
    [    1.203897] UDP hash table entries: 256 (order: 0, 4096 bytes)
    [    1.209824] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
    [    1.216481] NET: Registered protocol family 1
    [    1.221553] RPC: Registered named UNIX socket transport module.
    [    1.227523] RPC: Registered udp transport module.
    [    1.232358] RPC: Registered tcp transport module.
    [    1.237090] RPC: Registered tcp NFSv4.1 backchannel transport module.
    [    1.244715] hw perfevents: enabled with armv6_1176 PMU driver, 3 counters available
    [    1.252856] bcm2708_dma: DMA manager at f2007000
    [    1.257722] vc-mem: phys_addr:0x00000000 mem_base=0x1fa00000 mem_size:0x20000000(512 MiB)
    [    1.267467] futex hash table entries: 256 (order: -1, 3072 bytes)
    [    1.273963] audit: initializing netlink subsys (disabled)
    [    1.279550] audit: type=2000 audit(1.040:1): initialized
    [    1.300252] VFS: Disk quotas dquot_6.5.2
    [    1.304597] Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
    [    1.314054] FS-Cache: Netfs 'nfs' registered for caching
    [    1.321230] NFS: Registering the id_resolver key type
    [    1.326404] Key type id_resolver registered
    [    1.330752] Key type id_legacy registered
    [    1.336157] msgmni has been set to 965
    [    1.342563] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
    [    1.350583] io scheduler noop registered
    [    1.354566] io scheduler deadline registered (default)
    [    1.360313] io scheduler cfq registered
    [    1.366691] BCM2708FB: allocated DMA memory 5ec00000
    [    1.372002] BCM2708FB: allocated DMA channel 0 @ f2007000
    [    1.400415] Console: switching to colour frame buffer device 222x59
    [    1.424349] bcm2708-dmaengine bcm2708-dmaengine: Load BCM2835 DMA engine driver
    [    1.432394] uart-pl011 dev:f1: no DMA platform data
    [    1.438202] vc-cma: Videocore CMA driver
    [    1.442419] vc-cma: vc_cma_base      = 0x00000000
    [    1.447242] vc-cma: vc_cma_size      = 0x00000000 (0 MiB)
    [    1.452870] vc-cma: vc_cma_initial   = 0x00000000 (0 MiB)
    [    1.472108] brd: module loaded
    [    1.482618] loop: module loaded
    [    1.486391] vchiq: vchiq_init_state: slot_zero = 0xde800000, is_master = 0
    [    1.494517] Loading iSCSI transport class v2.0-870.
    [    1.501003] usbcore: registered new interface driver smsc95xx
    [    1.507015] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
    [    1.713423] Core Release: 2.80a
    [    1.716693] Setting default values for core params
    [    1.721737] Finished setting default values for core params
    [    1.927641] Using Buffer DMA mode
    [    1.931114] Periodic Transfer Interrupt Enhancement - disabled
    [    1.937085] Multiprocessor Interrupt Enhancement - disabled
    [    1.942830] OTG VER PARAM: 0, OTG VER FLAG: 0
    [    1.947304] Dedicated Tx FIFOs mode
    [    1.951311] WARN::dwc_otg_hcd_init:1047: FIQ DMA bounce buffers: virt = 0xdec14000 dma = 0x5ec14000 len=9024
    [    1.961432] FIQ FSM acceleration enabled for :
    [    1.961432] Non-periodic Split Transactions
    [    1.961432] Periodic Split Transactions
    [    1.961432] High-Speed Isochronous Endpoints
    [    1.988419] dwc_otg: Microframe scheduler enabled
    [    1.988555] WARN::hcd_init_fiq:412: FIQ on core 0 at 0xc03fad3c
    [    1.999618] WARN::hcd_init_fiq:413: FIQ ASM at 0xc03fb014 length 36
    [    2.010786] WARN::hcd_init_fiq:438: MPHI regs_base at 0xdf806000
    [    2.021956] dwc_otg bcm2708_usb: DWC OTG Controller
    [    2.032108] dwc_otg bcm2708_usb: new USB bus registered, assigned bus number 1
    [    2.044484] dwc_otg bcm2708_usb: irq 32, io mem 0x00000000
    [    2.055189] Init: Port Power? op_state=1
    [    2.064258] Init: Power Port (0)
    [    2.072854] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
    [    2.084875] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
    [    2.097156] usb usb1: Product: DWC OTG Controller
    [    2.106763] usb usb1: Manufacturer: Linux 3.18.11+ dwc_otg_hcd
    [    2.117658] usb usb1: SerialNumber: bcm2708_usb
    [    2.128263] hub 1-0:1.0: USB hub found
    [    2.137334] hub 1-0:1.0: 1 port detected
    [    2.147024] dwc_otg: FIQ enabled
    [    2.147050] dwc_otg: NAK holdoff enabled
    [    2.147064] dwc_otg: FIQ split-transaction FSM enabled
    [    2.147141] Module dwc_common_port init
    [    2.147812] usbcore: registered new interface driver usb-storage
    [    2.159411] mousedev: PS/2 mouse device common for all mice
    [    2.171046] bcm2835-cpufreq: min=700000 max=700000
    [    2.181554] sdhci: Secure Digital Host Controller Interface driver
    [    2.192764] sdhci: Copyright(c) Pierre Ossman
    [    2.202472] DMA channels allocated for the MMC driver
    [    2.239421] Load BCM2835 MMC driver
    [    2.253388] sdhci-pltfm: SDHCI platform and OF driver helper
    [    2.271721] ledtrig-cpu: registered to indicate activity on CPUs
    [    2.283266] hidraw: raw HID events driver (C) Jiri Kosina
    [    2.297263] usbcore: registered new interface driver usbhid
    [    2.307884] usbhid: USB HID core driver
    [    2.321507] TCP: cubic registered
    [    2.330097] Initializing XFRM netlink socket
    [    2.340723] Indeed it is in host mode hprt0 = 00021501
    [    2.353150] NET: Registered protocol family 17
    [    2.369413] Key type dns_resolver registered
    [    2.386724] mmc0: host does not support reading read-only switch, assuming write-enable
    [    2.401259] registered taskstats version 1
    [    2.429675] vc-sm: Videocore shared memory driver
    [    2.439935] mmc0: new high speed SDHC card at address 59b4
    [    2.459220] [vc_sm_connected_init]: start
    [    2.479266] mmcblk0: mmc0:59b4 USD   14.7 GiB 
    [    2.489545] vc_vchi_sm_init: failed to open VCHI service (-1)
    [    2.495285] [vc_sm_connected_init]: failed to initialize shared memory service
    [    2.521034] [vc_sm_connected_init]: end - returning -1
    [    2.533028]  mmcblk0: p1 p2 < p5 p6 > p3
    [    2.550114] EXT4-fs (mmcblk0p6): INFO: recovery required on readonly filesystem
    [    2.562911] EXT4-fs (mmcblk0p6): write access will be enabled during recovery
    [    2.639391] usb 1-1: new high-speed USB device number 2 using dwc_otg
    [    2.651493] Indeed it is in host mode hprt0 = 00001101
    [    2.774427] EXT4-fs (mmcblk0p6): recovery complete
    [    2.798660] EXT4-fs (mmcblk0p6): mounted filesystem with ordered data mode. Opts: (null)
    [    2.812167] VFS: Mounted root (ext4 filesystem) readonly on device 179:6.
    [    2.836739] devtmpfs: mounted
    [    2.846662] Freeing unused kernel memory: 336K (c079a000 - c07ee000)
    [    2.860023] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
    [    2.873753] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
    [    2.888287] hub 1-1:1.0: USB hub found
    [    2.898158] hub 1-1:1.0: 5 ports detected
    [    3.189477] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
    [    3.299729] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
    [    3.315092] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
    [    3.332557] smsc95xx v1.0.4
    [    3.405520] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:81:4a:a1
    [    3.509584] usb 1-1.2: new full-speed USB device number 4 using dwc_otg
    [    3.646989] usb 1-1.2: New USB device found, idVendor=046d, idProduct=c52b
    [    3.662219] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
    [    3.676037] usb 1-1.2: Product: USB Receiver
    [    3.688128] usb 1-1.2: Manufacturer: Logitech
    [    3.718087] input: Logitech USB Receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:046D:C52B.0001/input/input0
    [    3.756644] hid-generic 0003:046D:C52B.0001: input,hidraw0: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-bcm2708_usb-1.2/input0
    [    3.820604] input: Logitech USB Receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.1/0003:046D:C52B.0002/input/input1
    [    3.860616] hid-generic 0003:046D:C52B.0002: input,hiddev0,hidraw1: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-bcm2708_usb-1.2/input1
    [    3.918094] hid-generic 0003:046D:C52B.0003: hiddev0,hidraw2: USB HID v1.11 Device [Logitech USB Receiver] on usb-bcm2708_usb-1.2/input2
    [    4.889756] udevd[158]: starting version 175
    [    8.105413] random: nonblocking pool is initialized
    [   12.057055] EXT4-fs (mmcblk0p6): re-mounted. Opts: (null)
    [   12.560167] EXT4-fs (mmcblk0p6): re-mounted. Opts: (null)
    [   23.326355] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
    [   24.875311] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
    [   28.743759] cfg80211: Calling CRDA to update world regulatory domain
    [   32.100627] Adding 102396k swap on /var/swap.  Priority:-1 extents:1 across:102396k SSFS
    [   74.009453] usb 1-1.4: new high-speed USB device number 5 using dwc_otg
    [   74.111986] usb 1-1.4: New USB device found, idVendor=0bda, idProduct=8179
    [   74.112031] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
    [   74.112052] usb 1-1.4: Product: 802.11n WLAN NIC
    [   74.112071] usb 1-1.4: Manufacturer: Realtek
    [   74.249606] Unable to handle kernel paging request at virtual address 7e32d254
    [   74.261993] pgd = dd18c000
    [   74.270985] [7e32d254] *pgd=00000000
    [   74.280001] Internal error: Oops: 5 [#1] PREEMPT ARM
    [   74.289880] Modules linked in: 8188eu(O+) cfg80211 rfkill snd_bcm2835 snd_pcm snd_seq snd_seq_device snd_timer snd evdev joydev uio_pdrv_genirq uio
    [   74.308698] CPU: 0 PID: 2329 Comm: modprobe Tainted: G           O   3.18.11+ #781
    [   74.321564] task: dd245100 ti: ddfd4000 task.ti: ddfd4000
    [   74.332279] PC is at load_module+0x1948/0x1f1c
    [   74.341811] LR is at load_module+0x1934/0x1f1c
    [   74.351490] pc : [<c00886d0>]    lr : [<c00886bc>]    psr: 30000013
    [   74.351490] sp : ddfd5e88  ip : bf1a81c0  fp : ddfd5f44
    [   74.373345] r10: bf1a8058  r9 : 00000000  r8 : bf1a8064
    [   74.383843] r7 : c0557314  r6 : dd3ef4e0  r5 : 7e32d240  r4 : ddfd5f48
    [   74.395550] r3 : 00000000  r2 : 00000000  r1 : da5b7dc0  r0 : c0814280
    [   74.407339] Flags: nzCV  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
    [   74.419872] Control: 00c5387d  Table: 1d18c008  DAC: 00000015
    [   74.431055] Process modprobe (pid: 2329, stack limit = 0xddfd41b0)
    [   74.442519] Stack: (0xddfd5e88 to 0xddfd6000)
    [   74.452377] 5e80:                   bf1a8064 00007fff c0085714 c02fcd88 00000013 00000000
    [   74.466125] 5ea0: df9ae000 ddfd5f7c ddfd5f50 ddfd5eb8 00000000 bf1a8064 ddfd4008 bf1a80a0
    [   74.479747] 5ec0: bf1a81c0 00000000 b6cd0000 ddfd4000 00002db0 00000000 00000000 00000000
    [   74.493403] 5ee0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    [   74.507108] 5f00: 00000000 00000000 00000000 00000000 00000000 00000000 00000080 000e9725
    [   74.520767] 5f20: b6bec000 b6f02948 00000080 c000eaa8 ddfd4000 00000000 ddfd5fa4 ddfd5f48
    [   74.534393] 5f40: c0088d90 c0086d94 df9ae000 000e9725 dfa4f344 dfa4f1d6 dfa8d044 000a1ccc
    [   74.547937] 5f60: 000b245c 00000000 00000000 00000000 00000023 00000024 00000018 0000001c
    [   74.561425] 5f80: 0000000c 00000000 00000000 00000000 00060000 b74df608 00000000 ddfd5fa8
    [   74.574972] 5fa0: c000e800 c0088cb0 00000000 00060000 b6bec000 000e9725 b6f02948 b6bec000
    [   74.588535] 5fc0: 00000000 00060000 b74df608 00000080 b74ded58 000e9725 b6f02948 00000000
    [   74.602120] 5fe0: 00000000 befe090c b6ef9fb4 b6e64e94 60000010 b6bec000 00000000 00000000
    [   74.615733] [<c00886d0>] (load_module) from [<c0088d90>] (SyS_init_module+0xec/0x100)
    [   74.628903] [<c0088d90>] (SyS_init_module) from [<c000e800>] (ret_fast_syscall+0x0/0x48)
    [   74.642434] Code: e51bc084 e15c0005 e2455008 0a000009 (e5953014) 
    [   74.659323] ---[ end trace 9b95a96a348bea3c ]---

**Comment by sebastianbergmann** [comment]
Closing because I neither use the OS version nor the USB WLAN dongle anymore.

**Comment by lwfinger** [comment]
If you are not using the OS version or the dongle any more, why did you open this issue?

**Comment by sebastianbergmann** [comment]
Six hours ago I was still using them, sorry for the noise.
