### ISSUE TITLE
It keeps printing RxIdleAnt=MAIN_ANT to syslog

### ISSUE THREAD

**Issue by nisargjhaveri** [lwfinger/rtl8188eu#191]
`RxIdleAnt=MAIN_ANT` keeps showing up in my syslog every couple of seconds, with no other details or output. 

I'm on Raspbian. I've added this module using dkms.

```
$ uname -a
Linux raspberrypi 4.4.38+ #938 Thu Dec 15 15:17:54 GMT 2016 armv6l GNU/Linux
```

**Comment by lwfinger** [comment]
I silenced that message. I have no idea why you are seeing it as I do not in my tests.
