### ISSUE TITLE
RTL8188EUS is not reconized

### ISSUE THREAD

**Issue by ad1rie1** [lwfinger/rtl8188eu#206]
My wifi card TL-WN722N v2 is not reconized by the driver. 
it's possible to add the support ? 
pci id : 2357:010c
You can see the driver on TP-link website but on recent kernel it refuse to compile. 
can you help me ?

**Comment by lwfinger** [comment]
I pushed that change. In case this is not the correct driver, please let me know. In any case, close this issue.

**Comment by ad1rie1** [comment]
Thanck you very much :)
