### ISSUE TITLE
Monitor mode not supported

### ISSUE THREAD

**Issue by nikhilskynet** [lwfinger/rtl8188eu#217]
monitor mod is not working.im using kali linux.

**Comment by lwfinger** [comment]
This has been discussed many times in these threads. If you want monitor mode, you will have to add it to the driver. It was not put in by Realtek. No, I do not know why.

**Comment by ksabarianandhan** [comment]
Can you please Explain me how to install those drivers. Or You direct me to that link. as i'm a beginner i cant install those.Please help me

**Comment by nikhilskynet** [comment]
enter these in terminal

make all

sudo make install

copy rtl8188eufw.bin to /lib/firmware/rtlwifi/

**Comment by intersected** [comment]
@nikhilskynet thanks for the comment, but will that actually work ? will I be able to put adapter in monitor mode? 
Thanks

**Comment by nikhilskynet** [comment]
another driver by mfruba supports monitor mode...
https://github.com/mfruba/kernel

**Comment by alexey2baranov** [comment]
> enter these in terminal make all sudo make install copy rtl8188eufw.bin to /lib/firmware/rtlwifi/

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.10.0-kali7-amd64/build M=/home/kali/rtl8188eu  modules
make[1]: *** /lib/modules/5.10.0-kali7-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:155: modules] Error 2

**Comment by lwfinger** [comment]
As has been stated many times, you need to install your kernel headers.
