### ISSUE TITLE
What's the command to start the monitor mode?

### ISSUE THREAD

**Issue by Borduni** [lwfinger/rtl8188eu#226]
iwconfig wlan0 mode monitor and
airmon-ng wlan0 start

are not working. What should I do to start the monitor mode on my TP-WN722N v2?

**Comment by lwfinger** [comment]
This driver DOES NOT SUPPORT monitor mode. You can either fix the driver, or find one that supports that mode. I would suggest you look at rtl8xxxu in the mainline kernel.
