### ISSUE TITLE
rtl8818eus是否支持监听模式

### ISSUE THREAD

**Issue by 102464** [lwfinger/rtl8188eu#242]
监听模式好像用不了
root@ubuntu-OptiPlex-380:~# iwconfig
lo        no wireless extensions.

wlan0     unassociated  ESSID:""  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=0/100  Signal level=0 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

docker0   no wireless extensions.

eth0      no wireless extensions.

root@ubuntu-OptiPlex-380:~# ifconfig wlan0 down
root@ubuntu-OptiPlex-380:~# iwconfig wlan0 mode monitor 
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Invalid argument.
root@ubuntu-OptiPlex-380:~# ifconfig wlan0 up
root@ubuntu-OptiPlex-380:~# 
网卡：nw336

**Comment by lwfinger** [comment]
No, it cannot support monitor mode. If you want that feature, you will need to write it yourself.

**Comment by safal2000** [comment]
Hello there,
can u give me the written script of the code?? to write the driver

**Comment by sinlice** [comment]
您好 ，请问这个功能有加上吗

**Comment by lwfinger** [comment]
什么特点？
