### ISSUE TITLE
This driver does not support fedora

### ISSUE THREAD

**Issue by Flowertome** [lwfinger/rtl8188eu#250]
![2018-04-05 20-25-06](https://user-images.githubusercontent.com/9876749/38365582-72e2ae56-390f-11e8-904f-cbfa961f8359.png)

**Comment by Flowertome** [comment]
![2018-04-05 20-27-47](https://user-images.githubusercontent.com/9876749/38365682-d44b0f94-390f-11e8-82d4-3ba7df1d2ffc.png)

**Comment by lwfinger** [comment]
Sorry, I do not read Chinese. At least I think that is the language you have in those pictures.

The driver does support all versions of Fedora. Please write out the problem you are having, run the text through Google Translate, and post the resulting English. I suspect that you are missing the kernel headers package, or whatever Fedora calls it.

**Comment by amibal** [comment]
I'm running this on Fedora 27, works pretty good for me.
