### ISSUE TITLE
LED

### ISSUE THREAD

**Issue by tichun** [lwfinger/rtl8188eu#252]
Could LED be disabled?
It might be annoying and 'wasteful'.

**Comment by rkarlsba** [comment]
I made an attempt to fix this with a small patch, but I guess I don't know the code that well… Anyone with a clue?


[rtl8188-led.patch.txt](https://github.com/lwfinger/rtl8188eu/files/2228357/rtl8188-led.patch.txt)

**Comment by tichun** [comment]
Well.. my device has 'died' so.. I guess I should close this?
