### ISSUE TITLE
linux kernel 4.17 not support ！ attention

### ISSUE THREAD

**Issue by fafactx** [lwfinger/rtl8188eu#260]
attention  usb driver not support linux kernel 4.17 not support ！ attention

**Comment by lwfinger** [comment]
Attention: You are wrong. It builds just fine here on every kernel including 4.19-rc0. If you are using Ubuntu, then those idiots likely backported an API from a newer kernel. As I have stated many times before, I cannot keep track of all such changes, and I refuse to break the driver for everyone else. You will need to fix it yourself!!!
