### ISSUE TITLE
Realtek FTP logins for various drivers + v5.3.9

### ISSUE THREAD

**Issue by kimocoder** [lwfinger/rtl8188eu#275]
I've just probed through Realtek FTP's and found a decent new base,
The rtl8188eus has a fairly new release of v5.3.9_28540.20180627

New since v4.2.2.4
* Supports 802.11s MESH mode
* Android 8 support
* Miracast support
* Fix signal leakage when testing MKK
* Fix external LNA CSSK RSSI bug

Full changelog https://github.com/kimocoder/rtl8188eus/blob/v5.3.9/RTL8188EUS%20ReleaseNotes.pdf

FTP Server : ftp3.realtek.com
a)Account:RTL8192C Password: 3ubP7C (8188CUS/CTV/8192CU/8192CE)
b)Account:RTL8192D Password: a6dWF2 (8192DU)
c)Account:RTL8723 Password: F4v9Ws (8723AS/AS-VAU)
d)Account:RTL8188E Password: M6b3Er (8188EUS/ETV/8189ES)
e)Account:RTL8812A Password: J2e8Fg (8811AU/8812AU)
f)Account:RTL8192E Password: N5c6Sx (8192EU)
g)Account: RTL8723B Password: G3q6Wp (RTL8723B)

Hope some may be of interest? Anyhow, keep up your amazing work!

**Comment by epman100** [comment]
as of April 2020, it appears many of these account logins & passwords to the Realtek FTP server have stopped working and generate 530 authentication failed error messages.

**Comment by CGarces** [comment]
Ping @kimocoder 
How you get the version v5.7.0_34085.20200313 for rtl8812au?

**Comment by epman100** [comment]
a follow-up, it appears the ftp3.realtek.com site is recently dead and is no longer in service

**Comment by lwfinger** [comment]
That site has been dead for quite a while.
