### ISSUE TITLE
give error in kali 4.19.0

### ISSUE THREAD

**Issue by muratoznn** [lwfinger/rtl8188eu#276]
LD [M]  /root/Downloads/rtl8188eu-master/8188eu.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.18.0-kali2-amd64'

İt is stoppping why you know ?

**Comment by lwfinger** [comment]
Because it is dome. Creating 8188eu.ko is the final step of the build. To install it, you need to :sudo make install". Then you need to blacklist r8188eu and rtl8xxu (use Google to see how to do that), then reboot.
