### ISSUE TITLE
After last update Ubuntu 16.04, internet is unusable 

### ISSUE THREAD

**Issue by fpilee** [lwfinger/rtl8188eu#277]
Hello

I have upgraded my system yesterday and internet doesn't work anymore. I takes a minute to connect and then is just very slow. 

is Ubuntu 16.04, kernel was updated and my internet work so slow in my default wifi network, but it works fine on other. 
The only difference between networks is the Channel, wifi network with channel 4 doesn't work but the other with channel 9 works fine. And the one with Channel 9 is 150MB while channel 4 network is 72MB(132mb in iwconfig) 72 in wifi analizer windows.

Both networks worked fine before update with v4 branch. Now I have tried with version 5 and master and is the same.

![2019-02-14 10_12_10-wifi analyzer](https://user-images.githubusercontent.com/1960075/52789970-22b97680-3044-11e9-8b2a-27eef79a5d86.png)

**Comment by lwfinger** [comment]
Well, you change the user part of networking. The driver part does not change, but it stops working. Which part do you think might be wrong?

Which driver are you actually using? Is it r8188eu, rtl8xxxu, or 8188eu? If you want to use the GitHub driver with later kernels, you need to blacklist r8188eu and rtl8xxxu.
