### ISSUE TITLE
Fix uninitialized "auth algorithm" variable when sending auth seq=2 packet

### ISSUE THREAD

**Issue by pepa-cz** [lwfinger/rtl8188eu#279]
In branch v5.2.2.4, in function `issue_auth()` (`core/rtw_mlme_ext.c`) there is an unitialized value `le_val16` that leads to fill auth algorithm field in auth packet by a random value. 

Fix:
<pre>
From de918984e2cf416aeaceed78343a23aa61a6718c Mon Sep 17 00:00:00 2001
From: Pepa Hajek <hajekpepa@gmail.com>
Date: Wed, 27 Feb 2019 11:35:54 +0100
Subject: [PATCH] Fix uninitialized variable in auth seq=2 packet

Random value causes wrong "algorithm" field in the packect. Thus some wifi clients cannot connect to AP.
---
 core/rtw_mlme_ext.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/core/rtw_mlme_ext.c b/core/rtw_mlme_ext.c
index 1e41548..6cb646f 100755
--- a/core/rtw_mlme_ext.c
+++ b/core/rtw_mlme_ext.c
@@ -8129,7 +8129,7 @@ void issue_auth(_adapter *padapter, struct sta_info *psta, unsigned short status
        struct xmit_priv                        *pxmitpriv = &(padapter->xmitpriv);
        struct mlme_ext_priv    *pmlmeext = &(padapter->mlmeextpriv);
        struct mlme_ext_info    *pmlmeinfo = &(pmlmeext->mlmext_info);
-       __le16 le_val16;
+       __le16 le_val16 = 0;
 #ifdef CONFIG_RTW_80211R
        struct mlme_priv        *pmlmepriv = &(padapter->mlmepriv);
        ft_priv                 *pftpriv = &pmlmepriv->ftpriv;
--
2.18.0
</pre>

**Comment by lwfinger** [comment]
Thanks for the report. I think the following patch makes it clearer what is happening, and removes one if test that is totally unnecessary.

diff --git a/core/rtw_mlme_ext.c b/core/rtw_mlme_ext.c
index dd84fb2..fc2b6eb 100755
--- a/core/rtw_mlme_ext.c
+++ b/core/rtw_mlme_ext.c
@@ -8176,12 +8176,11 @@ void issue_auth(_adapter *padapter, struct sta_info *psta, unsigned short status
                /* setting auth algo number */
                val16 = (u16)psta->authalg;
 
-               if (status != _STATS_SUCCESSFUL_)
-                       le_val16 = 0;
-
                if (val16)      {
                        le_val16 = cpu_to_le16(val16);
                        use_shared_key = 1;
+               } else {
+                       le_val16 = 0;
                }
 
                pframe = rtw_set_fixed_ie(pframe, _AUTH_ALGM_NUM_, (unsigned char *)&le_val16, &(pattrib->pktlen));
