### ISSUE TITLE
Typo in mlme_linux. Compile fails if kernel < 4.15

### ISSUE THREAD

**Issue by fgimenezm** [lwfinger/rtl8188eu#283]
https://github.com/lwfinger/rtl8188eu/blob/5b7d51d871b8d5234e538012331304f6cb8790c1/os_dep/mlme_linux.c#L123

"istatic" instead of "static" on mlme_linux.c#L123 from branch v5.2.2.4

**Comment by lwfinger** [comment]
Fixed. Sorry for the problem.
