### ISSUE TITLE
does support 0bda:b711?

### ISSUE THREAD

**Issue by wjx0912** [lwfinger/rtl8188eu#285]
the device is   mw150us usb wifi, 

root@nv-desktop:/home/nv# lsusb 
Bus 001 Device 004: ID 0bda:b711 Realtek Semiconductor Corp. 

the commands:

usb_modeswitch -KW -v 0bda -p 1a2b
insmod /home/nv/8188eu.ko
echo 0bda b711 | tee > /sys/bus/usb/drivers/r8188eu/new_id

but it do a iwconfig, it shows 'Operation not permitted':

root@nv-desktop:/home/nv# iwconfig wlan0 txpower off
Error for wireless request "Set Tx Power" (8B26) :
    SET failed on device wlan0 ; Operation not permitted.

any idea about the chip?thanks

**Comment by lwfinger** [comment]
Why do you ask about the chip? That error says that the driver does not implement the "Set TX Power" operation, nothing more.
