### ISSUE TITLE
Add TP-Link TL-WN727N v5.21 support

### ISSUE THREAD

**Issue by kakash1hatake** [lwfinger/rtl8188eu#296]
Hello.
I've found out that usb dongle TP-Link TL-WN727N v5.21 is based on rtl8188eus chipset.
And I can use this driver with it.
But when compiling the driver I need to edit the file os_dep/usb_intf.c to add my device id.
When running lsusb I see 2357:0111, so I added a line
`{USB_DEVICE(0x2357, 0x0111)}, /* TP-Link TL-WN727N v5.21 */`
to the rtw_usb_id_tbl structure.

I've forked the repo and commited the new code
https://github.com/kakash1hatake/rtl8188eu/commit/86124c66f31eda27de7a087c3d87c13bb65eda5d

**Comment by lwfinger** [comment]
I got the new device ID. Thanks.
