### ISSUE TITLE
Kernel panic (5.4.2)

### ISSUE THREAD

**Issue by lpapp** [lwfinger/rtl8188eu#300]
It seems that the current code causes kernel panic when plugging the device in. Would you be able to advise me how to proceed from here?
![IMG_20191206_133324341_BURST000_COVER_TOP](https://user-images.githubusercontent.com/141957/70326840-6e384d80-182d-11ea-897b-907ce78d83a7.jpg)
![IMG_20191206_133324341_BURST001](https://user-images.githubusercontent.com/141957/70326842-6e384d80-182d-11ea-8d26-7af39cdf057e.jpg)
![IMG_20191206_133319074_BURST001](https://user-images.githubusercontent.com/141957/70326843-6e384d80-182d-11ea-8bc6-2ea70a0a730d.jpg)

Some more information about the environment in case it is helpful:

lpapp ~ $ sudo dkms install 8188eu/1.0

8188eu.ko.xz:
Running module version sanity check.

Good news! Module version v5.2.2.4_25483.20171222 for 8188eu.ko.xz
exactly matches what is already found in kernel 5.4.2-arch1-1.
DKMS will not replace this module.
You may override by specifying --force.

depmod........

DKMS: install completed.
lpapp ~ $ 

[ 1657.195753] audit: type=1101 audit(1575638953.024:270): pid=10009 uid=1000 auid=1000 ses=1 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="lpapp" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/3 res=success'
[ 1657.196027] audit: type=1110 audit(1575638953.024:271): pid=10009 uid=0 auid=1000 ses=1 msg='op=PAM:setcred grantors=pam_unix,pam_permit,pam_env acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/3 res=success'
[ 1657.201961] audit: type=1105 audit(1575638953.031:272): pid=10009 uid=0 auid=1000 ses=1 msg='op=PAM:session_open grantors=pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/3 res=success'
[ 1657.250676] 8188eu: loading out-of-tree module taints kernel.
[ 1657.251108] 8188eu: module verification failed: signature and/or required key missing - tainting kernel
[ 1657.258346] RTW: rtl8188eu v5.2.2.4_25483.20171222 
[ 1657.258347] RTW: build time: Dec  6 2019 13:27:13
[ 1657.258383] usbcore: registered new interface driver rtl8188eu
[ 1657.259178] audit: type=1106 audit(1575638953.087:273): pid=10009 uid=0 auid=1000 ses=1 msg='op=PAM:session_close grantors=pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/3 res=success'
[ 1657.259243] audit: type=1104 audit(1575638953.087:274): pid=10009 uid=0 auid=1000 ses=1 msg='op=PAM:setcred grantors=pam_unix,pam_permit,pam_env acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/3 res=success'

lsmod | grep 8188eu
8188eu               1617920  0
cfg80211              851968  1 8188eu

Bus 002 Device 002: ID 0bda:8179 Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter

                 *-usb
                      description: Generic USB device
                      product: 802.11n NIC
                      vendor: Realtek
                      physical id: 1
                      bus info: usb@2:1
                      version: 0.00
                      serial: 00E04C0001
                      capabilities: usb-2.00
                      configuration: driver=r8188eu maxpower=500mA speed=480Mbit/s

TP-LINK 
Model: TL-WN725N

**Comment by lwfinger** [comment]
DO NOT EVER SEND ME PRIVATE E-MAIL UNLESS I ASK FOR IT.

I only learned of this crash this morning even though the fundamental cause has been present since kernel 5.3. For the most part, I check the drivers to see if they build, not that they run.

Your crash pictures are better than nothing, but they do not show me the cause. I had to find my 8188eu device and look at the output of dmesg before the kernel had a panic. That showed me the fix, which has been pushed to the repo. The driver now works for me.

**Comment by lpapp** [comment]
Thanks! I was going to make a video for you. I could not capture anything in the rolling kernel panic screen. All the important information had rolled out the latest screen. And I could not scroll back.

**Comment by lpapp** [comment]
By the way, are you planning to port all these changes in this repo back to the mainline kernel? Then, we would not have to go to external places like this and use dkms, etc.

**Comment by lwfinger** [comment]
Absolutely not. To get the driver into a shape that it would be accepted into the kernel would take almost a year of full-time work, and no one has offered to support such an undertaking!

**Comment by lpapp** [comment]
Oh, I see. That is quite a lot of work for just one driver out of the many, many. :)

Thank you for maintaining this at least!
