### ISSUE TITLE
Weak wifi signal with TP-Link wn725n

### ISSUE THREAD

**Issue by Mozz4rt** [lwfinger/rtl8188eu#305]
Hello, first of all thank you for the driver! (and the time and effort put on it).

I installed it on my Fedora 31 desktop via make. The wifi signal got weaker than it was on my windows 10. Is there anything i can do to improve this?

My OS info: 
`Linux localhost.localdomain 5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

and the adapter is a TP-Link WN725N.

If there's anything else i can help with, let me know. And once again, thank you!

**Comment by lwfinger** [comment]
If you are using the master branch, you may find some improvement with the v5.2.2.4 branch. Otherwise there is nothing I can do.
