### ISSUE TITLE
I'm uploaded the latest rtl8188eu driver from realtek, please check it.

### ISSUE THREAD

**Issue by LazyZhu** [lwfinger/rtl8188eu#31]
It included driver, documents, wireless_tools, etc.

http://lazyzhu.com/file/RTL8188EUS_RTL8189ES_linux_v4.1.8_9499.20131104.zip

**Comment by davebradley14620** [comment]
Thanks LazyZhu.   I know this is an old thread.  Do you have your latest code somewhere else?

**Comment by LazyZhu** [comment]
@davebradley14620
http://dl.lazyzhu.com/file/RTL8188EU/

**Comment by elpetak** [comment]
@LazyZhu do you know if it's by design that version 4.3.0.7 has no firmware in it ?
