### ISSUE TITLE
Installed but not working for RTL8188GU

### ISSUE THREAD

**Issue by ulanproger** [lwfinger/rtl8188eu#315]
Hi, lwfinger!
I followed the instructions and successfully installed the driver (I copied rtl8188eufw.bin to /lib/firmware/rtlwifi/). But Wi-Fi settings is still saying: "No adapter found". 
My usb wifi adaper is RTL8188GU. Is this driver compatible with RTL8188GU?
System information:
Fedora 31
kernel ver. 5.4.15-200.fc31.x86_64
Thank you!

**Comment by lwfinger** [comment]
I do not think so. The only way to tell is to get the USB ID using lsusb, and then add that ID to the USB_DEVICE table.

**Comment by 19chang19** [comment]
this rtlwifi 
vid pid is 
Device 008: ID 0bda:b711 Realtek Semiconductor Corp

not working

**Comment by lwfinger** [comment]
If you added that USB ID to the driver, and it still failed, then the driver will NEVER support that device. In case you do not know how to do that, find the line that says 
 static struct usb_device_id rtw_usb_id_tbl[] = {
in file os_dep/usb_intf.c, and add a line that says 
USB_DEVICE(USB_VENDER_ID_REALTEK, 0xb711), .driver_info = RTL8188E},
right after it.

I could not find any Linux drivers on the web.

**Comment by TOB5894** [comment]
@19chang19  Does it work now?

**Comment by cslizhang** [comment]
I try,it doesn't work for rtl8188gu.

**Comment by lwfinger** [comment]
It is likely a totally different device. Good luck finding a driver.
