### ISSUE TITLE
Donation? Support?

### ISSUE THREAD

**Issue by kemitchell** [lwfinger/rtl8188eu#322]
Thanks very much for this work! I am stuck at home due to the virus, and only got my Debian desktop online thanks to this driver. It's so nice to be able to work that way.

@lwfinger, can I send you a few dollars via PayPal, Square Cash, Stripe, or the like? Feel free to e-mail me privately: kyle@kemitchell.com.

By the by, I see some really inappropriate feedback here, like #307. I know that has to be discouraging. But maybe it helps to read from me what you already know yourself: Feel free to ignore that noise. You deserve better.

**Comment by lwfinger** [comment]
Thanks for the kind words. No, I do not accept donations for my work, which is done on a volunteer basis. If you really want to help, make that donation to a local food pantry, or some other organization that is helping support the people that have been thrown out of work. I have been retired for nearly 21 years, and my future is secure.

I do ignore, for the most part, noise like that idiot. Unfortunately, the only negative feedback they get is that their requests for help are ignored.
