### ISSUE TITLE
Makefile:155: modules

### ISSUE THREAD

**Issue by php717** [lwfinger/rtl8188eu#324]
root@kali:~/tmp/rtl8188eu# sudo make all
make ARCH=arm CROSS_COMPILE= -C /lib/modules/3.4.113-g8ba25daf/build M=/root/tmp/rtl8188eu  modules
make[1]: *** /lib/modules/3.4.113-g8ba25daf/build: No such file or directory.  Stop.
make: *** [Makefile:155: modules] Error 2

plz explain .. whay its saying this for make ?
 No such file or directory.  Stop.
it suppose to create directory ? 

or im not getting somethings ?

**Comment by php717** [comment]
kernel headers incorrect ... got it

**Comment by lwfinger** [comment]
Exactly.
