### ISSUE TITLE
"make" not working

### ISSUE THREAD

**Issue by tanupreet121** [lwfinger/rtl8188eu#333]
Trying to install drivers for Tp-link wn722n. It was working just fine but after updating kernel update it is showing this error
root@kali:~# cd rtl8188eus/
root@kali:~/rtl8188eus# sudo -i
root@kali:~# echo "blacklist r8188eu.ko" > "/etc/modprobe.d/realtek.conf"
root@kali:~# exit
logout
root@kali:~/rtl8188eus# make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.19.0-kali4-amd64/build M=/root/rtl8188eus  modules
make[1]: *** /lib/modules/4.19.0-kali4-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:2047: modules] Error 2

**Comment by lwfinger** [comment]
Did you see the part in README.md that says you need to install kernel headers?
