### ISSUE TITLE
i'm using a tp-link wifi adapter TL-WN722N v3.0 on my ubuntu 20 virtual box...I NEED HELP!

### ISSUE THREAD

**Issue by laracroft86** [lwfinger/rtl8188eu#335]
ark66@mark66-VirtualBox:~$ iwconfig 
wlxd037456f87a8  unassociated  ESSID:""  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

lo        no wireless extensions.

enp0s3    no wireless extensions.

enp0s8    no wireless extensions.

mark66@mark66-VirtualBox:~$ ifconfig
enp0s3: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 08:00:27:3c:63:82  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 590 (590.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 56  bytes 6520 (6.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::e399:7ad2:a21d:5247  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:71:36:00  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 483  bytes 77940 (77.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 11759  bytes 958102 (958.1 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11759  bytes 958102 (958.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlxd037456f87a8: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether d0:37:45:6f:87:a8  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

mark66@mark66-VirtualBox:~$ sudo ifconfig wlxd037456f87a8 down
mark66@mark66-VirtualBox:~$ sudo airmon-ng start wlxd037456f87a8

Found 2 processes that could cause trouble.
Kill them using 'airmon-ng check kill' before putting
the card in monitor mode, they will interfere by changing channels
and sometimes putting the interface back in managed mode

    PID Name
   5262 NetworkManager
   5291 wpa_supplicant

PHY	Interface	Driver		Chipset

null	wlxd037456f87a8	r8188eu		TP-Link TL-WN722N v2

mark66@mark66-VirtualBox:~$ iwconfig
wlxd037456f87a8  unassociated  ESSID:""  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

lo        no wireless extensions.

enp0s3    no wireless extensions.

enp0s8    no wireless extensions.

mark66@mark66-VirtualBox:~$ airmon-ng check kill
Run it as root
mark66@mark66-VirtualBox:~$ sudo airmon-ng check kill

Killing these processes:

    PID Name
   5262 NetworkManager
   5291 wpa_supplicant

mark66@mark66-VirtualBox:~$ airmon-ng start wlxd037456f87a8
Run it as root
mark66@mark66-VirtualBox:~$ sudo airmon-ng start wlxd037456f87a8

PHY	Interface	Driver		Chipset

null	wlxd037456f87a8	r8188eu		TP-Link TL-WN722N v2

mark66@mark66-VirtualBox:~$ iwconfig
wlxd037456f87a8  unassociated  ESSID:""  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

lo        no wireless extensions.

enp0s3    no wireless extensions.

enp0s8    no wireless extensions.

mark66@mark66-VirtualBox:~$ iwconfig wlxd037456f87a8 mode monitor
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlxd037456f87a8 ; Operation not permitted.
mark66@mark66-VirtualBox:~$ 
mark66@mark66-VirtualBox:~$ 
mark66@mark66-VirtualBox:~$ 
mark66@mark66-VirtualBox:~$ 
mark66@mark66-VirtualBox:~$ 
mark66@mark66-VirtualBox:~$ uname -ra
Linux mark66-VirtualBox 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
mark66@mark66-VirtualBox:~$ uname -r
5.4.0-42-generic
mark66@mark66-VirtualBox:~$

**Comment by lwfinger** [comment]
If you are trying to get monitor mode, the master branch has never worked. Branch v5.2.2.4 may support it, but I do not.
