### ISSUE TITLE
How do I disable TSSI error in the source code, this error will be printed to the tty in large quantities

### ISSUE THREAD

**Issue by softincl** [lwfinger/rtl8188eu#337]
![IMG_20200826_120436_917](https://user-images.githubusercontent.com/66812949/91254217-55454300-e794-11ea-980e-e02c1558e6b6.jpg)

**Comment by lwfinger** [comment]
How should I know? That message does not come from any Realtek chip.

**Comment by softincl** [comment]
I use this kind of network card, the chip is rtl
![MW150US_0](https://user-images.githubusercontent.com/66812949/91255130-a9512700-e796-11ea-9894-a2f22122d012.jpg)

**Comment by lwfinger** [comment]
The mt7601u is a Media Tek chip. Please post the output of lsusb.
