### ISSUE TITLE
rtlwifi_new GIT is missing

### ISSUE THREAD

**Issue by mng4** [lwfinger/rtl8188eu#341]
I'm trying to install Realtek RTL8723DE driver in Fedora and most of the articles guiding me to https://github.com/lwfinger/rtlwifi_new.git. But the problem is GIT is missing. Any help would be appreciated

**Comment by dubhater** [comment]
8723de is officially supported in recent kernels. I'm not sure which version first got support, but the current one, 5.8, has it. If you can't update your kernel, https://github.com/lwfinger/rtw88 is the repo you want.
