### ISSUE TITLE
Add support for Edimax N150 Wi-Fi 4 Nano USB Adapter

### ISSUE THREAD

**Issue by sim0nx** [lwfinger/rtl8188eu#351]
Hi,

I have opened a PR #350 to add support for the Edimax EW-7811Un V2. It is supported by this driver, only the IDs are missing. I have successfully tested this by adding the device ID to *os_dep/usb_intf.c*.

Thanks

**Comment by lwfinger** [comment]
The patch is merged. Thanks. I also added that device to the v5.2.2.4 branch.
