### ISSUE TITLE
cannot see wifi-ssids below is the dmesg result

### ISSUE THREAD

**Issue by openOrganizationPakistan** [lwfinger/rtl8188eu#356]
no wifi is listed to connect dmesg shows this

[    5.045739] caller _nv032125rm+0x2d/0x60 [nvidia] mapping multiple BARs
[    5.072563] usb 5-1: New USB device found, idVendor=1a2c, idProduct=0043, bcdDevice= 1.10
[    5.072565] usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    5.072566] usb 5-1: Product: USB Mouse
[    5.072567] usb 5-1: Manufacturer: SEMICCHIP
[    5.088894] input: SEMICCHIP USB Mouse as /devices/pci0000:00/0000:00:1a.2/usb5/5-1/5-1:1.0/0003:1A2C:0043.0003/input/input21
[    5.089006] hid-generic 0003:1A2C:0043.0003: input,hidraw0: USB HID v1.10 Mouse [SEMICCHIP USB Mouse] on usb-0000:00:1a.2-1/input0
[    5.192689] resource sanity check: requesting [mem 0x000c0000-0x000fffff], which spans more than pnp 00:07 [mem 0x000d8000-0x000e7fff]
[    5.192968] caller _nv000709rm+0x1af/0x200 [nvidia] mapping multiple BARs
[    5.950166] [drm] Initialized nvidia-drm 0.0.0 20160202 for 0000:0f:00.0 on minor 0
[   12.658097] usb 5-1: USB disconnect, device number 4
[   13.384072] usb 5-1: new low-speed USB device number 5 using uhci_hcd
[   13.557606] usb 5-1: New USB device found, idVendor=1a2c, idProduct=0043, bcdDevice= 1.10
[   13.557609] usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   13.557611] usb 5-1: Product: USB Mouse
[   13.557613] usb 5-1: Manufacturer: SEMICCHIP
[   13.573882] input: SEMICCHIP USB Mouse as /devices/pci0000:00/0000:00:1a.2/usb5/5-1/5-1:1.0/0003:1A2C:0043.0004/input/input22
[   13.574038] hid-generic 0003:1A2C:0043.0004: input,hidraw0: USB HID v1.10 Mouse [SEMICCHIP USB Mouse] on usb-0000:00:1a.2-1/input0
[   26.162114] usb 5-1: USB disconnect, device number 5
[   26.880056] usb 5-1: new low-speed USB device number 6 using uhci_hcd
[   27.053616] usb 5-1: New USB device found, idVendor=1a2c, idProduct=0043, bcdDevice= 1.10
[   27.053619] usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   27.053621] usb 5-1: Product: USB Mouse
[   27.053623] usb 5-1: Manufacturer: SEMICCHIP
[   27.069938] input: SEMICCHIP USB Mouse as /devices/pci0000:00/0000:00:1a.2/usb5/5-1/5-1:1.0/0003:1A2C:0043.0005/input/input23
[   27.070095] hid-generic 0003:1A2C:0043.0005: input,hidraw0: USB HID v1.10 Mouse [SEMICCHIP USB Mouse] on usb-0000:00:1a.2-1/input0
[   31.162079] usb 5-1: USB disconnect, device number 6
[   31.632064] usb 5-1: new low-speed USB device number 7 using uhci_hcd
[   31.805618] usb 5-1: New USB device found, idVendor=1a2c, idProduct=0043, bcdDevice= 1.10
[   31.805621] usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   31.805622] usb 5-1: Product: USB Mouse
[   31.805624] usb 5-1: Manufacturer: SEMICCHIP
[   31.821910] input: SEMICCHIP USB Mouse as /devices/pci0000:00/0000:00:1a.2/usb5/5-1/5-1:1.0/0003:1A2C:0043.0006/input/input24
[   31.822069] hid-generic 0003:1A2C:0043.0006: input,hidraw0: USB HID v1.10 Mouse [SEMICCHIP USB Mouse] on usb-0000:00:1a.2-1/input0
[   38.162080] usb 5-1: USB disconnect, device number 7
[   38.880068] usb 5-1: new low-speed USB device number 8 using uhci_hcd
[   39.053650] usb 5-1: New USB device found, idVendor=1a2c, idProduct=0043, bcdDevice= 1.10
[   39.053653] usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   39.053655] usb 5-1: Product: USB Mouse
[   39.053657] usb 5-1: Manufacturer: SEMICCHIP
[   39.069925] input: SEMICCHIP USB Mouse as /devices/pci0000:00/0000:00:1a.2/usb5/5-1/5-1:1.0/0003:1A2C:0043.0007/input/input25
[   39.070084] hid-generic 0003:1A2C:0043.0007: input,hidraw0: USB HID v1.10 Mouse [SEMICCHIP USB Mouse] on usb-0000:00:1a.2-1/input0
[   48.914093] usb 5-1: USB disconnect, device number 8
[   49.632076] usb 5-1: new low-speed USB device number 9 using uhci_hcd
[   49.805655] usb 5-1: New USB device found, idVendor=1a2c, idProduct=0043, bcdDevice= 1.10
[   49.805658] usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   49.805660] usb 5-1: Product: USB Mouse
[   49.805662] usb 5-1: Manufacturer: SEMICCHIP
[   49.820935] input: SEMICCHIP USB Mouse as /devices/pci0000:00/0000:00:1a.2/usb5/5-1/5-1:1.0/0003:1A2C:0043.0008/input/input26
[   49.821099] hid-generic 0003:1A2C:0043.0008: input,hidraw0: USB HID v1.10 Mouse [SEMICCHIP USB Mouse] on usb-0000:00:1a.2-1/input0
[   64.658121] usb 5-1: USB disconnect, device number 9
[   65.384066] usb 5-1: new low-speed USB device number 10 using uhci_hcd
[   65.557667] usb 5-1: New USB device found, idVendor=1a2c, idProduct=0043, bcdDevice= 1.10
[   65.557670] usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   65.557672] usb 5-1: Product: USB Mouse
[   65.557674] usb 5-1: Manufacturer: SEMICCHIP
[   65.573947] input: SEMICCHIP USB Mouse as /devices/pci0000:00/0000:00:1a.2/usb5/5-1/5-1:1.0/0003:1A2C:0043.0009/input/input27
[   65.574109] hid-generic 0003:1A2C:0043.0009: input,hidraw0: USB HID v1.10 Mouse [SEMICCHIP USB Mouse] on usb-0000:00:1a.2-1/input0
[   73.115079] EEPROM ID(0x0) is invalid!!
[   73.115080] EEPROM ID = 0x0000
[   73.115662] usbcore: registered new interface driver r8188eu
[   73.130648] r8188eu 2-3:1.0 wlp0s29f7u3: renamed from wlan0
[   73.172680] kauditd_printk_skb: 93 callbacks suppressed
[   73.172682] audit: type=1130 audit(1609068686.677:104): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-udev-settle comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   73.187281] loop: module loaded
[   73.259889] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[   73.367188] audit: type=1130 audit(1609068686.872:105): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dracut-shutdown comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   73.381333] audit: type=1130 audit(1609068686.886:106): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=plymouth-read-write comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   73.395355] audit: type=1130 audit(1609068686.900:107): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=import-state comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   73.485113] audit: type=1130 audit(1609068686.990:108): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-tmpfiles-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   73.490061] audit: type=1334 audit(1609068686.995:109): prog-id=26 op=LOAD
[   73.539527] RPC: Registered named UNIX socket transport module.
[   73.539529] RPC: Registered udp transport module.
[   73.539529] RPC: Registered tcp transport module.
[   73.539530] RPC: Registered tcp NFSv4.1 backchannel transport module.
[   74.595225] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   74.595986] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   80.809857] process '/usr/bin/anydesk' started with executable stack
[   81.201880] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[   81.213450] tun: Universal TUN/TAP device driver, 1.6
[   81.214543] virbr0: port 1(virbr0-nic) entered blocking state
[   81.214545] virbr0: port 1(virbr0-nic) entered disabled state
[   81.214606] device virbr0-nic entered promiscuous mode
[   81.598237] virbr0: port 1(virbr0-nic) entered blocking state
[   81.598239] virbr0: port 1(virbr0-nic) entered listening state
[   81.734824] virbr0: port 1(virbr0-nic) entered disabled state
[   85.662843] rfkill: input handler disabled
[  102.353539] rfkill: input handler enabled
[  106.470204] rfkill: input handler disabled

I'll provide any help you might need about the issue ASAP...

**Comment by lwfinger** [comment]
What device do you have? Please post the output of 'lsusb'.

**Comment by openOrganizationPakistan** [comment]
Sorry issue solved yesterday. I just reinstall OS and drivers and this seems to solve the issue.
My device by the way is rtl8188eu
