### ISSUE TITLE
TL-WN727n problem: Direct firmware load for regulatory.db failed with error -2

### ISSUE THREAD

**Issue by Zaryob** [lwfinger/rtl8188eu#361]
Hi,
I'm using TP-Link TL-WN727n adaptor. In the documentation it says that, USB WiFi dongle comes with rtl8188eus chip. I found its source code provided by Archer, it wouldn't work then I found that repository.

I have built kernel module and modprobed. It seems no problem after modprobe. However, I connected to USB and it come with that error.  I'm gonna sharing screenshot of it.

**Comment by Zaryob** [comment]
![IMG_20210218_232843](https://user-images.githubusercontent.com/22801690/108418015-b92b5e80-7241-11eb-95ec-d71ad86c4668.jpg)

**Comment by Zaryob** [comment]
This is not about the RHEL. Im using various systems (Fedora, RHEL, Ubuntu) and all of them not worked this dongle as well. 

Im using also kernel-ml 5.11.0 with RHEL.

**Comment by Zaryob** [comment]
Addition: ID of bus device output provied by `lsusb` is 
```
ID 2357:0111 TP-Link
```

**Comment by lwfinger** [comment]
The missing file is regulatory.db which is not a part of this driver. You should be able to get that from your distro.
