### ISSUE TITLE
TL-WN725N, TL-WN722N V3 adapters in AP mode on Nvidia Jetson Nano 2GB, branch v5.2.2.4 work. Need to correct Makefile

### ISSUE THREAD

**Issue by alpop** [lwfinger/rtl8188eu#363]
TL-WN725N, TL-WN722N V3 adapters in AP mode on Nvidia Jetson Nano 2GB with driver built from branch v5.2.2.4 work OK. I needed to correct Makefile in order to build driver for ARM64 platform (step 4)

1. built OS from  image file downloaded a month ago from NVIDIA's site : jetson-nano-jp45-sd-card-image.zip
2. git clone --branch=v5.2.2.4 https://github.com/lwfinger/rtl8188eu
3. cd rtl8188eu
4. replaced  line 403 in Makefile with the following line (taken from master brancn's Makefile):
SUBARCH := $(shell uname -m | sed -e "s/i.86/i386/; s/ppc.*/powerpc/; s/armv.l/arm/; s/aarch64/arm64/;")
5. make
5. sudo make install
6. blacklisted r8188eu by creating file /etc/modprobe.d/wireless.conf with the line:
    blacklist r8188eu
7. rebooted
8. created hotspot with nm-connection-editor, nmcli should be OK, too
9. successfully connected to hotspot on my NVIDIA jetson device from iPhones and iPads,
   stable connections with either huge high-gain antenna TL-WN722N thing or tiny TL-WN725N dongle,
   static IP's though,  dhcp and names resolving need additional efforts
10. many great  thanks to @lwfinger

**Comment by lwfinger** [comment]
Makefile fixed today. Thanks for the note.
