### ISSUE TITLE
LED not blinking after installing the driver for TP-Link TL-WN722N v2.

### ISSUE THREAD

**Issue by d4rk-c1ph3r** [lwfinger/rtl8188eu#365]
Monitor mode and packet injection working perfectly. Chipset is rtl8188eu

**Comment by wegi1** [comment]
Did you check in any other device where LED is blinking in exactly this one dongle?
Maybe basically LED is burned?

**Comment by gr33nm0nk2802** [comment]
LED works fine on windows. Also mt7601u drivers support led blinking

**Comment by wegi1** [comment]
> LED works fine on windows. Also mt7601u drivers support led blinking

On my dongle working as well on the Linux and WIN10 booth 64bits.

But you can't have d4rk-c1ph3r dongle where can exist any problem like:
- LED is damaged
- LED doesn't exist
- Code version had disable support of LED blinking
- ... any other possible driver or hardware errors

That's way I'd ask d4rk-c1ph3r hi is sure in his dongle LED exist.

**Comment by gr33nm0nk2802** [comment]
The problem lies i  the code itself. I have the same adapter

**Comment by wegi1** [comment]
> The problem lies in the code itself. I have the same adapter .
> 
> LED working on windows hence not broken.
> LED detected first time when connected before installing driver on ubuntu

Possible. You can't be sure you have this same adapter like d4rk-c1ph3r. As lwfinger mentioned in #342 they are medels without LED.

BUT as you said in last words you have right - most probably the code is here the problem.

**Comment by gr33nm0nk2802** [comment]
Yes its the same adapter v2/3 having same chipset and a green LED which blinks initially and after driver installation everything works fine except LED blinking

**Comment by wegi1** [comment]
So resolve is in #342
Uncomment LED blinking code.

**Comment by gr33nm0nk2802** [comment]
I don't see similar code in this version could you mention the version.

**Comment by lwfinger** [comment]
My 8188eu device does not have a LED, thus you are on your own to get it working! That is the beauty of open source.

**Comment by d4rk-c1ph3r** [comment]
@lwfinger can you help me with some resources to understand and write my own code. I have never written code about drivers

**Comment by lwfinger** [comment]
That is well above my pay grade. If you checkout branch v4.1.8_9499, your LED should work.
