### ISSUE TITLE
Error! Could not find module source directory. Directory: /usr/src/.-rtl8188eu does not exist.

### ISSUE THREAD

**Issue by FranZurirata** [lwfinger/rtl8188eu#367]
Hi, I was following this guide https://askubuntu.com/questions/1170202/how-to-install-rtl8188eus-driver-on-ubuntu-18-04/1170249#1170249?newreg=d7ad664cc52143edb5356f451016ab40

to install the driver in Kalo and when I get to the "sudo dkms add ./rtl8188eu" part I get that error, I'm new to this, what could be the mistake? thanks

**Comment by lwfinger** [comment]
Did you read this part? "lwfinger has now said[1] he will no longer support dkms and has removed[2] the dkms.conf from the repository. Notes: [1] github.com/lwfinger/rtl8188eu/issues/306#issuecomment-579312568 [2] github.com/lwfinger/rtl8188eu/commit/… – Dominic Sayers Sep 26 '20 at 12:19 "
