### ISSUE TITLE
TP-Link TL-WN722N wrong signal strength

### ISSUE THREAD

**Issue by BabaJi-0** [lwfinger/rtl8188eu#391]
![wifi](https://user-images.githubusercontent.com/92249486/146646577-c56bae59-e07a-454d-ae14-001884ea4d59.jpg)
I am using Fedora 35 with latest stable kernel. I am maybe wrong but I am writing this issue here since i think it upstream. btw, I installed the drivers few months from here and had the same issue.

**Comment by lwfinger** [comment]
Signal strength is not a quantity that comes from the connection. It is always derived. If you do not like the numbers, then please modify the code and submit the changes. That is the way of open-source.

The signal should be gotten from a 'sudo iw dev <dev_name> scan | egrep "SSID|signal"'

When I run this command, I get the following for the RTL8188EU:
        signal: -45.00 dBm
        SSID: Larry_ac
        signal: -45.00 dBm
        SSID: NETGEAR81

When I run the same command for a Intel Corporation Wireless 7260, I get:
        signal: -30.00 dBm
        SSID: NETGEAR81
        signal: -35.00 dBm
        SSID: Larry_ac

For a Realtek RTL8852AE, I get:
        signal: -26.00 dBm
        SSID: Larry_ac
        signal: -33.00 dBm
        SSID: NETGEAR81

As you can see, the numbers do bounce around a bit, bit in the absence of a radio-quiet setup with known attenuation, it is not possible to know which of the above is more correct than the others. In addition, the antenna placement and strength is a variable that cannot be controlled in an inexpensive  USB dongle.
