### ISSUE TITLE
Error for wireless request "Set Mode" (8B06) :     SET failed on device wlan0 ; Invalid argument.

### ISSUE THREAD

**Issue by rlelchev** [lwfinger/rtl8188eu#395]
I am unable to set my wireless adapter to monitor mode. I am running "sudo iwconfig wlan0 mode monitor" and it returns this error message. Any help?

**Comment by lwfinger** [comment]
It means that the driver does not support monitor mode, or that your system is not configured to handle IWEXT calls.
