### ISSUE TITLE
Add example on how to DKMS install/remove method?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [lwfinger/rtl8188eu#425]
Add example on how to DKMS install/remove method?  Maybe something similar to how https://github.com/morrownr/8821au-20210708 does?

**Comment by lwfinger** [comment]
I do not do or support DKMS. If you want an update, then you NEED to prepare the patch!!!!!!

**Comment by Jibun-no-Kage** [comment]
Ah!  I guess when I saw the dkms.conf file I was thinking at one time you had considered DKMS?  Well if was an idea.

**Comment by lwfinger** [comment]
Someone else wrote it and I added their patch. I did not do the work.
