### ISSUE TITLE
Monitor mode support

### ISSUE THREAD

**Issue by slav0nic** [lwfinger/rtl8188eu#73]
Will be fine have monitor mode support in this driver

**Comment by alex-chan** [comment]
Interested. This chip has a lot of cheap wnics(Like TPLINK TL725, MW150UH) sold in market. How I wish the monitor mode could be implemented  as soon as possible.

**Comment by AlexanderSelzer** [comment]
:+1: you can currently get a TL-WN725N for 7€, monitor mode would be amazing

**Comment by AgelxNash** [comment]
@lwfinger commented on [2 Oct 2013](https://github.com/lwfinger/rtl8188eu/issues/15#issuecomment-25545980): 
```It is known that monitor mode does not work. For me, that is a very low priority problem. If you find the fix, please send it to me; however, I will not be working on this problem.```

But I hope that in 2015, priorities can be changed...

**Comment by IlyaBizyaev** [comment]
Same wish...

**Comment by NicolasNarvaez** [comment]
same wish, still hopeful u.u

**Comment by lhk-pf** [comment]
same wish

**Comment by bebinalpha** [comment]
wishing for the same feature.

**Comment by jsitnicki** [comment]
It is not monitor mode support, but if you're is looking only for a capture of raw 802.11 frames that get sent/received you can try the rtl8188eu driver from the Linux kernel with this patch on top: jsitnicki/linux@d70efced56a04958a28d1133b201b7b62467ecd7. Short explanation of how to get it running can be found [here](https://lkml.kernel.org/g/1441383439-27007-1-git-send-email-jsitnicki@gmail.com). If there's interest I can try porting the patch to the driver version in this repo.

**Comment by lwfinger** [comment]
Why not submit that patch for inclusion in the kernel source?

**Comment by jsitnicki** [comment]
I've posted it as a RFC to linux-wireless a few days ago ([link](http://article.gmane.org/gmane.linux.kernel.wireless.general/141622)) to see if it will attract interest, since the monitor interface isn't on the TODO list for the rtl8188eu in-kernel driver, and the patch is not making use of cfg80211. But sure, I can resubmit as a proposed patch, if you see value it.

**Comment by hkparker** [comment]
Would love to get this working.  Not super experienced writing drivers but if you can give me and idea of what would be needed to get it working @lwfinger I'll try to make a PR if I can.

**Comment by tvsijin** [comment]
Any updates?

**Comment by christopherdupont** [comment]
Any updates ?

**Comment by miramango** [comment]
Any updates ?

**Comment by REPTILEHAUS** [comment]
Can anyone tell me is there a difference between the rtl8188eu driver and the rtl8188eus driver ?

I have and Alfa AWUS036NHV wireless adapter that I have been trying for 2 days to get working in a Kali VirtualBox VM on a Mac host machine but nothing is working.. Ive downloaded the rtl8188eu driver and enabled it etc etc but still it wont show up on the VM..

**Comment by lwfinger** [comment]
Without your posting any messages, there is no way to tell if the driver is configured for the USB ID of the Alfa AWUS036NHV. In fact, we don't even know what ID that device uses. In the VM, does it show up in a 'lsusb' command?

**Comment by REPTILEHAUS** [comment]
First problem was that the adapter wouldn't show up at all in VirtualBox, I got a copy of VMware fusion and a new copy of the latest Kali and it connects etc no problem now. 

Next up I am having issues with setting it in monitor mode.. According to airmon-ng the driver is r8188eu and the chipset is RTL8188EUS, I have read all over the web including here that this driver is not capable of true monitor mode. So I guess my question now is it a useless piece of kit for wireless pentesting or is there some hack/patch that can be made to it to enable monitor mode ? Thank you in advance and some output from dmesg and airmon-ng below 👍 

dmesg -wH:

[Sep23 18:07] usb 2-2: new high-speed USB device number 4 using ehci-pci
[  +0.145141] usb 2-2: New USB device found, idVendor=0bda, idProduct=8179
[  +0.000005] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  +0.000003] usb 2-2: Product: 802.11n NIC
[  +0.000002] usb 2-2: Manufacturer: Realtek
[  +0.541706] Chip Version Info: CHIP_8188E_Normal_Chip_TSMC_D_CUT_1T1R_RomVer(0)
[  +0.169301] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  +0.022100] r8188eu 2-2:1.0: firmware: direct-loading firmware rtlwifi/rtl8188eufw.bin
[  +5.674083] MAC Address = 00:c0:ca:87:50:98
[  +0.036999] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  +0.043670] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[Sep23 18:08] R8188EU: ERROR assoc success
[  +0.000038] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready







airmon-ng:

PHY    Interface    Driver        Chipset

null    wlan0        r8188eu        Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter

**Comment by OzanU** [comment]
http://xiaopan.co/forums/threads/rtl8188eus-alfa-036nhv.9328/ 
Support Monitor mode driver. Would like to hear if its working.

**Comment by tvsijin** [comment]
the driver is seems to be for 4.3 kernel.. make seems failed (may be because i am on ubuntu 16.04LTS with kernel 4.4)

**Comment by lwfinger** [comment]
If you post the error, I can likely help you get the driver built for kernel 4.4.

**Comment by tomasjonnes** [comment]
It won't compile in new kernels by itself as some things have change since the release of this driver, though you can find it in the AUR with the patches to make it work (I think it is the same version than the mediafire's link posted before): https://aur.archlinux.org/packages/8188eu-dkms/

I've compiled it succesfully but I don't have any card to test it now.
I would also like to hear if monitor mode is now possible (and useful) in Linux.

**Comment by tvsijin** [comment]
Can u give me the instructions to get it compiled on my machine..
Ubuntu 16.04
Kernel 4.4.0

**Comment by tvsijin** [comment]
Not working.. still cant put interface in monitor mode...

**Comment by prathm3107** [comment]
Any updates about monitor mode support??? 
(unfortunately ordered wrong version of wn722n with realtek chipset ;-;

**Comment by aliakcza** [comment]
I join this question

**Comment by lwfinger** [comment]
Driver rtl8xxxu in mainline is the only driver for the RTL8188EU that will ever have monitor mode UNLESS on of you submits a patch. I will only commit to making patches for kernel API changes that cause the build to fail!

**Comment by pranavgupta1234** [comment]
Is monitor mode supported now ?

**Comment by stevanuscolonne** [comment]
Please make it support monitor mode, I've learned every things about linux & kali by my self, just bought TP WN722N, but sadly it use Realtek Chip. Really grateful if some one can make it support monitor mode.

**Comment by Josue198s** [comment]
I have the same issue with TP-LINK WN822N..

**Comment by lwfinger** [comment]
The reason that the driver is open source is so that people that need a missing function can add it and then share their code with the community.

Unless one of you puts up real money, or are willing to do the work, monitor mode support is not going to be added.

Please be aware that kernel mainline driver rtl8xxxu is where future development for Realtek USB devices will take place. At the moment, the RTL8188EU is not supported by that driver, but that would be a good place for someone to work. BTW, that driver does have the full complement of mac80211 services, including monitor mode.

**Comment by arsalan86** [comment]
I'm using the 8188eu driver from the package firmware-realtek

this driver doesn't seem to support monitor mode for either the 722n or the 725n

is there a driver anywhere that can support monitor mode for either of these devices?

**Comment by dimitrisA** [comment]
There is this repo. Couldn't get monitor mode to work. Read that some people could. https://github.com/mfruba/kernel 

I'm keeping my v2 adapter. Maybe in a future not far far away monitor mode will be enabled. :)

**Comment by Himura2la** [comment]
I have TL-WN723N v3 and also waiting for full support

**Comment by Jhony33** [comment]
Not working too

**Comment by Hoeistnou** [comment]
I am busy for a couple weeks with no results either... :(

**Comment by iods2** [comment]
it looks like this driver is dead for the time being , as it been out there for like 3  years and still no support for monitor mode, the only solution would be to actually buy a new USB NIC that actually supports monitor mode and packet injection.
so can u please folks out there provide us with a list of all the available chipsets that provides those two functionalities ?
thanks

**Comment by b4551k5** [comment]
I was able to enter monitor mode using this driver: https://github.com/kimocoder/rtl8188eu
on 4.14.0-kali3-amd64 with awus036nhv cs wifi card. I found the driver in the kali linux forum posted by
kimocoder.
I did the following:

1. Downloaded the driver
2. make (compiled without errors on 4.14.0-kali3-amd64) (maybe you need to get linux-headers-amd64)
3. make install
4. rmmod r8188eu
5. insmod 8188eu.ko
6. maybe unplug and plug-in wifi card
7. lshw -c net --> should show rtl8188eu as driver NOT r8188eu

You should now be able to enter monitor mode via
ifconfig wlan0 down
iwconfig wlan0 mode monitor
ifconfig wlan0 up

I did not test it on a fresh installation of kali and have tried several things before, but I think this should do the trick. At least it is worth a try.

**Comment by piluex** [comment]
Nevermind, new repo: https://github.com/kimocoder/rtl8188eus
it works with monitor mode for the tp link 722n confirmed on arch linux.

**Comment by kimocoder** [comment]
@piluex I've also added packet injection support, but haven't tested it

**Comment by ail603601** [comment]
OH GOD!!!

I FOUND THE WAY TO INSTALL DRIVER AND ALSO PUT DEVICE IN DAMN MONITOR MODE 

ON KENREL 4.18.0
and i think it will work(99%) for bellow kenrel versions also


HOW?

JUST FOLLOW THIS LINK

https://github.com/ail603601/rtl8188eus

**Comment by lwfinger** [comment]
Despite all the shouting and the misspelling, any patches should be submitted back to this branch. I assume it was the parent for yours.

**Comment by kimocoder** [comment]
Adding injection to the rtl8188eu when I'm back home.

**Comment by chidiezenyem** [comment]
Hi Kimcoder, are you back home? Could you post the updated link? Thanks in advance

**Comment by Sparsh9088** [comment]
For those who are still searching for monitor mode for this driver. https://github.com/AIRCRACK-NG/RTL8188EUS . Install this driver. It supports monitor mode

**Comment by sanyam8929** [comment]
nothing is working and tp link wn725n is not going in monitor mode ....
pls update the page with new pacthes

**Comment by lwfinger** [comment]
Use the driver in the previous comment. If it does not work create an issue here. I will NEVER add those patches to the master branch here, and the v5.2.2.4 branch does not need them.

**Comment by kimocoder** [comment]
Use v5.3.9 branch, not v5.7.6.1.
