### ISSUE TITLE
disable led support for 8188eu

### ISSUE THREAD

**Issue by BARBAZ** [lwfinger/rtl8188eu#82]
Hi
Sorry I'm totally noob at drivers programming but I was wondering in which way I can modify this driver to disable led support ? I tried several thing but I'm still getting compilation errors. Or led always ON but I can't turn it off at all.

**Comment by tljohnsn** [comment]
I would like to disable the led completely.   It is annoying when it blinks at night.

Is there a way to do it?

I tried:
options r8188eu led_enable=0
and
options r8188eu rtw_led_enable=0

no joy.

**Comment by tljohnsn** [comment]
I rebuilt from source and got it to work on raspberry pi os buster:
sudo apt-get install raspberrypi-kernel-headers
git clone https://github.com/lwfinger/rtl8188eu.git
cd rtl8188eu
make
sudo make install
echo "options 8188eu rtw_led_enable=0" | sudo tee -a /etc/modprobe.d/wlan.conf

**Comment by lwfinger** [comment]
At line 151 of include/autoconf.h, there is a statement that says
#define CONFIG_LED

To disable LEDS completely, insert // at the beginning of that line to turn it into a comment.

**Comment by Daniel-Ebert** [comment]
> I rebuilt from source and got it to work on raspberry pi os buster: sudo apt-get install raspberrypi-kernel-headers git clone https://github.com/lwfinger/rtl8188eu.git cd rtl8188eu make sudo make install echo "options 8188eu rtw_led_enable=0" | sudo tee -a /etc/modprobe.d/wlan.conf

Thank you very much, this works perfectly for me! :)
