### ISSUE TITLE
iw command not working

### ISSUE THREAD

**Issue by adhi-balaji** [lwfinger/rtl8188eu#84]
I know this issue had been raised a year ago. But i just want to clarify when will cfg80211 support will be added to the driver in this repo or i want to know whether cfg80211 support had been added in the kernel version

**Comment by kirkins** [comment]
+1 having a similar issue. Anyone find a good work around?

https://unix.stackexchange.com/questions/401413/iw-dev-interface-scan-not-working-on-embedded-device

**Comment by lwfinger** [comment]
The basic problem is that the driver does not use or understand the cfg80211 commands on which iw is based. You need to find a driver for the RTL8188EU that implements cfg80211!
