### ISSUE TITLE
problem with make install on raspbian 3.12.36+ #737

### ISSUE THREAD

**Issue by BARBAZ** [lwfinger/rtl8188eu#89]
I Noticed an error when compiling this driver.
Compilation works fine but make install return an error.
FATAL: Module r8188eu not found 
I manage to install it by myself but ... make install didn't work

**Comment by lwfinger** [comment]
That error was the result of some novice crashing his system because he had both r8188eu and 8188eu loaded.  I just pushed a fix that should work even when the kernel driver is not part of the system.
